"""
generate_60_day_logbook_fixed.py

Fixed version of the logbook generator that avoids KeyError from .format() and CSS braces.
Generates 60_day_logbook.md starting 16 Sep 2025, two days per A4 page (stacked vertically).
"""

from datetime import date, timedelta

# ---------- Config ----------
START_DATE = date(2025, 9, 16)   # starts tomorrow as requested
NUM_DAYS = 60
OUTPUT_MD = "60_day_logbook.md"
# ----------------------------

WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

def fmt_date(d: date):
    return f"{d.strftime('%a')}, {d.day} {d.strftime('%b')} {d.year}"

def hour_label(hour):
    start = f"{hour:02d}:00"
    end_hour = hour + 1
    end = "24:00" if end_hour == 24 else f"{end_hour:02d}:00"
    return f"{start} — {end}"

def make_hour_table():
    rows = []
    for h in range(24):
        rows.append(
            "        <tr>\n"
            f"          <td class=\"hour\">{hour_label(h)}</td>\n"
            "          <td class=\"expected\">&nbsp;</td>\n"
            "          <td class=\"actual\">&nbsp;</td>\n"
            "        </tr>\n"
        )
    table = (
        "      <table class=\"hour-table\" cellspacing=\"0\">\n"
        "        <thead>\n"
        "          <tr><th class=\"hour\">Hour</th><th>Expected</th><th>Actual</th></tr>\n"
        "        </thead>\n"
        "        <tbody>\n"
        + "".join(rows) +
        "        </tbody>\n"
        "      </table>\n"
    )
    return table

def make_day_block(current_date: date):
    day_header = f"<h2 class=\"date\">{fmt_date(current_date)}</h2>\n"
    hour_table = make_hour_table()
    eod = (
        "      <div class=\"eod\">\n"
        "        <h3>End-of-day Review</h3>\n        <table class=\"eod-table\" cellspacing=\"0\">\n"
        "          <tr><td>Today's wins / highlights:</td><td class=\"fill\">&nbsp;</td></tr>\n"
        "          <tr><td>Top 3 tasks planned vs done:</td><td class=\"fill\">&nbsp;</td></tr>\n"
        "          <tr><td>Energy (1-10):</td><td class=\"fill\">&nbsp;</td></tr>\n"
        "          <tr><td>Notes / Obstacles:</td><td class=\"fill tall\">&nbsp;</td></tr>\n"
        "        </table>\n"
        "      </div>\n"
    )
    improvement = (
        "      <div class=\"improvement\">\n"
        "        <h3>Improvement Box</h3>\n"
        "        <div class=\"improv-fill\">&nbsp;</div>\n"
        "      </div>\n"
    )
    signature = (
        "      <div class=\"signature\">\n"
        "        <span>Signature: ____________________________</span>\n"
        "      </div>\n"
    )

    block = (
        f"<div class=\"day-block\">\n"
        f"{day_header}\n"
        f"{hour_table}\n"
        f"{eod}\n"
        f"{improvement}\n"
        f"{signature}\n"
        f"</div>\n"
    )
    return block

def generate_md(start_date: date, days: int, out_file: str):
    css = """<style>
/* Page & layout */
@page { size: A4 portrait; margin: 10mm; }
body { font-family: Arial, sans-serif; font-size: 11pt; margin:0; padding:0; }
h1 { text-align:center; }
/* Each day-block is set to half A4 height using mm units so two day-blocks stack exactly on an A4 page */
.day-block { height: 148mm; box-sizing: border-box; padding: 6mm 8mm; border-bottom: 1px solid #444; }
.date { margin: 0 0 6px 0; font-size: 13pt; }
/* Dense hour table */
.hour-table { width: 100%; border-collapse: collapse; font-size: 10.5pt; }
.hour-table th, .hour-table td { border: 1px solid #999; padding: 4px 6px; }
.hour-table th { background: #f6f6f6; font-weight:600; }
.hour { width: 16%; white-space: nowrap; }
.expected { width: 42%; }
.actual { width: 42%; }
/* End-of-day review */
.eod { margin-top: 6px; }
.eod h3 { margin: 6px 0; font-size:11pt; }
.eod-table { width:100%; border-collapse: collapse; font-size: 10.5pt; }
.eod-table td { border:1px solid #999; padding:6px; }
.eod-table .fill { width:70%; }
.eod-table .tall { height: 36px; }
.improvement { margin-top:6px; }
.improvement h3 { margin:6px 0; font-size:11pt; }
.improv-fill { border:1px solid #999; height:38px; padding:6px; }
.signature { margin-top:8px; }
/* Page break after each physical A4 page (2 day-blocks) */
.page-break { page-break-after: always; }
</style>

"""

    with open(out_file, "w", encoding="utf-8") as f:
        f.write("<!-- 60-day logbook generated by generate_60_day_logbook_fixed.py -->\n\n")
        # write CSS (plain string, no formatting)
        f.write(css)
        # write the small header line using an f-string (safe)
        f.write(f"# 60-Day Time Management Logbook\n\n_Start date: {start_date.strftime('%d %b %Y')} | {days} days_\n\n")

        current = start_date
        written_days = 0
        page_count = 0
        while written_days < days:
            # First day on the page (top half)
            f.write(make_day_block(current))
            written_days += 1
            current += timedelta(days=1)

            # Second day on the page (bottom half) if available
            if written_days < days:
                f.write(make_day_block(current))
                written_days += 1
                current += timedelta(days=1)
            else:
                # If odd number, leave the second half blank but styled
                f.write(
                    "<div class=\"day-block\">\n"
                    "<h2 class=\"date\">&nbsp;</h2>\n"
                    "<div style=\"height:120mm\">&nbsp;</div>\n"
                    "</div>\n"
                )

            # Page break
            f.write("<div class=\"page-break\"></div>\n\n")
            page_count += 1

    print(f"Generated {out_file} — {days} days across {page_count} pages (two days per page).")

if __name__ == "__main__":
    generate_md(START_DATE, NUM_DAYS, OUTPUT_MD)
